name: nf-core-crisprvar-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
    ## bioconda packages
  - crispresso2=2.0.29
  - multiqc=1.7
  - fastqc=0.11.8
  - trim-galore=0.6.2
